//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/articles.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/forward.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/home.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/newarticle.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/return.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("images/search.png")]


